-- MySQL Script generated by MySQL Workbench
-- Mon 18 Mar 2024 03:34:50 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fifth_db` DEFAULT CHARACTER SET utf8 ;
USE `fifth_db` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`users` (
                                              `user_id`      BIGINT(255) NOT NULL AUTO_INCREMENT,
                                              `username`     VARCHAR(45) NOT NULL,
                                              `phone_number` VARCHAR(45) NOT NULL,
                                              `email`        VARCHAR(45) NULL,
                                              `password`     VARCHAR(45) NULL,
                                              PRIMARY KEY (`user_id`),
                                              UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
                                              UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`roles` (
                                              `role_id`       BIGINT(255) NOT NULL AUTO_INCREMENT,
                                              `name`          VARCHAR(45) NULL,
                                              `users_user_id` BIGINT(255) NOT NULL,
                                              PRIMARY KEY (`role_id`),
                                              INDEX `fk_roles_users1_idx` (`users_user_id` ASC) VISIBLE,
                                              CONSTRAINT `fk_roles_users1`
                                                  FOREIGN KEY (`users_user_id`)
                                                      REFERENCES `fifth_db`.`users` (`user_id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`events` (
                                               `event_id`      BIGINT(255) NOT NULL AUTO_INCREMENT,
                                               `date`          DATETIME    NULL,
                                               `title`         VARCHAR(45) NULL,
                                               `description`   VARCHAR(45) NULL,
                                               `users_user_id` BIGINT(255) NOT NULL,
                                               PRIMARY KEY (`event_id`),
                                               INDEX `fk_events_users1_idx` (`users_user_id` ASC) VISIBLE,
                                               CONSTRAINT `fk_events_users1`
                                                   FOREIGN KEY (`users_user_id`)
                                                       REFERENCES `fifth_db`.`users` (`user_id`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`publications` (
                                                     `publicacion_id` BIGINT(255)  NOT NULL AUTO_INCREMENT,
                                                     `title`          VARCHAR(45)  NOT NULL,
                                                     `body`           VARCHAR(255) NOT NULL,
                                                     `users_user_id`  BIGINT(255)  NOT NULL,
                                                     PRIMARY KEY (`publicacion_id`),
                                                     UNIQUE INDEX `publicacion_id_UNIQUE` (`publicacion_id` ASC) VISIBLE,
                                                     INDEX `fk_publications_users1_idx` (`users_user_id` ASC) VISIBLE,
                                                     CONSTRAINT `fk_publications_users1`
                                                         FOREIGN KEY (`users_user_id`)
                                                             REFERENCES `fifth_db`.`users` (`user_id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stream`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`stream` (
                                               `stream_id`   BIGINT(255)  NOT NULL AUTO_INCREMENT,
                                               `stream_data` VARCHAR(255) NULL,
                                               PRIMARY KEY (`stream_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`resources` (
                                                  `resource_id` BIGINT(255) NOT NULL AUTO_INCREMENT,
                                                  `resource_url` VARCHAR(45) NOT NULL,
                                                  PRIMARY KEY (`resource_id`),
                                                  UNIQUE INDEX `resource_url_UNIQUE` (`resource_url` ASC) VISIBLE,
                                                  UNIQUE INDEX `resource_id_UNIQUE` (`resource_id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publication_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`publication_comment`(
                                                           `comment_id` BIGINT(255) NOT NULL AUTO_INCREMENT,
                                                           `comment_body` VARCHAR(255) NULL,
                                                           `publications_publicacion_id` BIGINT(255) NOT NULL,
                                                           `users_user_id` BIGINT(255) NOT NULL,
                                                           PRIMARY KEY (`comment_id`),
                                                           INDEX `fk_comment_publications1_idx` (`publications_publicacion_id` ASC) VISIBLE,
                                                           INDEX `fk_publication_comment_users1_idx` (`users_user_id` ASC) VISIBLE,
                                                           CONSTRAINT `fk_comment_publications1`
                                                               FOREIGN KEY (`publications_publicacion_id`)
                                                                   REFERENCES `fifth_db`.`publications` (`publicacion_id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_publication_comment_users1`
                                                               FOREIGN KEY (`users_user_id`)
                                                                   REFERENCES `fifth_db`.`users` (`user_id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stream_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`stream_comments`(
                                                       `comment_id` BIGINT(255) NOT NULL AUTO_INCREMENT,
                                                       `comment_body` VARCHAR(45) NULL,
                                                       `stream_stream_id` BIGINT(255) NOT NULL,
                                                       `users_user_id` BIGINT(255) NOT NULL,
                                                       PRIMARY KEY (`comment_id`),
                                                       INDEX `fk_stream_comments_stream1_idx` (`stream_stream_id` ASC) VISIBLE,
                                                       INDEX `fk_stream_comments_users1_idx` (`users_user_id` ASC) VISIBLE,
                                                       CONSTRAINT `fk_stream_comments_stream1`
                                                           FOREIGN KEY (`stream_stream_id`)
                                                               REFERENCES `fifth_db`.`stream` (`stream_id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_stream_comments_users1`
                                                           FOREIGN KEY (`users_user_id`)
                                                               REFERENCES `fifth_db`.`users` (`user_id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`user_resources` (
                                                       `user_resource_id` BIGINT(255) NOT NULL AUTO_INCREMENT,
                                                       `resource_type` ENUM('PROFILE_PICTURE', 'ANY_PICTURE') NULL,
                                                       `resources_resource_id` BIGINT(255) NOT NULL,
                                                       `users_user_id` BIGINT(255) NOT NULL,
                                                       PRIMARY KEY (`user_resource_id`),
                                                       INDEX `fk_user_resources_resources1_idx` (`resources_resource_id` ASC) VISIBLE,
                                                       INDEX `fk_user_resources_users1_idx` (`users_user_id` ASC) VISIBLE,
                                                       CONSTRAINT `fk_user_resources_resources1`
                                                           FOREIGN KEY (`resources_resource_id`)
                                                               REFERENCES `fifth_db`.`resources` (`resource_id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_user_resources_users1`
                                                           FOREIGN KEY (`users_user_id`)
                                                               REFERENCES `fifth_db`.`users` (`user_id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacion_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`publicacion_resources` (
                                                              `publication_resource_id` BIGINT(255) NOT NULL AUTO_INCREMENT,
                                                              `resource_type` ENUM('POST_FRONT', 'POST_PICTURE', 'POST_VIDEO', 'POST_FILE') NULL,
                                                              `publications_publicacion_id` BIGINT(255) NOT NULL,
                                                              `resources_resource_id` BIGINT(255) NOT NULL,
                                                              PRIMARY KEY (`publication_resource_id`),
                                                              INDEX `fk_publicacion_resources_publications1_idx` (`publications_publicacion_id` ASC) VISIBLE,
                                                              INDEX `fk_publicacion_resources_resources1_idx` (`resources_resource_id` ASC) VISIBLE,
                                                              CONSTRAINT `fk_publicacion_resources_publications1`
                                                                  FOREIGN KEY (`publications_publicacion_id`)
                                                                      REFERENCES `fifth_db`.`publications` (`publicacion_id`)
                                                                      ON DELETE NO ACTION
                                                                      ON UPDATE NO ACTION,
                                                              CONSTRAINT `fk_publicacion_resources_resources1`
                                                                  FOREIGN KEY (`resources_resource_id`)
    REFERENCES `fifth_db`.`resources` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifth_db`.`event_resources` (
  `event_resource_id`     BIGINT(255) NOT NULL AUTO_INCREMENT,
  `resources_resource_id` BIGINT(255) NOT NULL,
  `events_event_id`       BIGINT(255) NOT NULL,
  PRIMARY KEY (`event_resource_id`),
  INDEX `fk_event_resources_resources1_idx` (`resources_resource_id` ASC) VISIBLE,
  INDEX `fk_event_resources_events1_idx` (`events_event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_resources_resources1`
    FOREIGN KEY (`resources_resource_id`)
    REFERENCES `fifth_db`.`resources` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_resources_events1`
    FOREIGN KEY (`events_event_id`)
    REFERENCES `fifth_db`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
